name = "reactr-foo"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "reactr.foo/*", zone_name = "reactr.foo" }
]

[[d1_databases]]
binding = "DB"
database_name = "reactr-foo"
database_id = "debbffbe-0fae-4cdc-aee5-67e8c39ff823"
migrations_dir = "migrations"
